---
global:
  scrape_interval: "15s"
scrape_configs:
- job_name: "prometheus"
  static_configs:
  - targets:
    - "localhost:9090"
- job_name: "api-gateway"
  static_configs:
  - targets:
    - "api-gateway:8080"
- job_name: "discovery-server"
  static_configs:
  - targets:
    - "discovery-server:8761"
- job_name: "user-service"
  static_configs:
  - targets:
    - "user-service:8081"
- job_name: "category-service"
  static_configs:
  - targets:
    - "category-service:8082"
- job_name: "sync-service"
  static_configs:
  - targets:
    - "sync-service:8083"
- job_name: "stock-service"
  static_configs:
  - targets:
    - "stock-service:8084"
- job_name: "payment-service"
  static_configs:
  - targets:
    - "payment-service:8089"
