_format_version: "3.0"

services:
  - name: web-service
    url: http://api-gateway:8080
    routes:
      - name: echo
        paths:
          - /
        hosts:
          - localhost

    # Uncomment and configure upstreams if needed
    # upstreams:
    #   - name: example_upstream
    #     targets:
    #       - target: 172.29.242.56:6969
    #         weight: 100
    #       - target: 172.29.242.56:7070
    #         weight: 50

    # Uncomment and configure plugins if needed
plugins:
   - name: file-log
     config:
       path: /file.log
       reopen: false

   - name: cors
     config:
       origins:
         - "*"
       methods:
         - GET
         - POST
       headers:
         - Accept
         - Accept-Version
         - Content-Length
         - Content-MD5
         - Content-Type
         - Date
         - X-Auth-Token
         - Authorization
       exposed_headers:
         - X-Auth-Token
       credentials: true
       max_age: 3600
       preflight_continue: false

    #   - name: rate-limiting
    #     config:
    #       second: 5
    #       hour: 10
    #       policy: local

    #   - name: ip-restriction
    #     config:
    #       allow:
    #         - 54.13.21.1
    #         - 143.1.0.0/24
    #       deny:
    #         - 54.13.21.0/24
    #       status: 401
    #       message: "Cannot grant access"

